general:
  buildTool: "docker"
  containerImageName: "afdendy/fe-ui5"
  containerImageTag: "linux"
  containerRegistryUrl: "hub.docker.com"
service:
  automaticVersioning: false
  dockerConfigJsonSecretTextCredentialsId: "dockercred"
  Acceptance:
    kubeConfigSecretTextCredentialsId: "kymacred"
  Release:
    kubeConfigSecretTextCredentialsId: "mykymacred"
steps:
  kanikoExecute:
    dockerfilePath: "docker/Dockerfile"
  artifactPrepareVersion:
    filePath: "docker/Dockerfile"
stages:
  Build:
    kanikoExecute: true
  Acceptance:
    kubernetesDeploy: true
    deployTool: "kubectl"
    namespace: "dev"
    appTemplate: "k8s/deployment-all.yaml"
    deployCommand: "apply"
  Release:
    kubernetesDeploy: true
    deployTool: "kubectl"
    namespace: "prod"
    createDockerRegistrySecret: false
    appTemplate: "k8s/deployment-all.yaml"
    deployCommand: "apply"
