general:
  buildTool: "docker"
  containerImageName: "afdendy/fe-ui5-mssql"
  containerImageTag: "linux"
  containerRegistryUrl: "https://hub.docker.com/repositories/afdendy"
service:
  automaticVersioning: false
  dockerConfigJsonSecretTextCredentialsId: "dockercred"
  Acceptance:
    kubeConfigSecretTextCredentialsId: "kymacred"
steps:
  kanikoExecute:
    dockerfilePath: "docker/Dockerfile"
  artifactPrepareVersion:
    filePath: "docker/Dockerfile"
stages:
  Build:
    kanikoExecute: false
  Acceptance:
    kubernetesDeploy: true
    deployTool: "kubectl"
    namespace: "mytest"
    createDockerRegistrySecret: false
    appTemplate: "k8s/deployment.yaml"
    deployCommand: "apply"
  Release:
    kubernetesDeploy: false
