kind: ConfigMap
apiVersion: v1
metadata:
  name: fe-ui5-mssql-my
  labels:
    app: fe-ui5-mssql-my
data:
  config.json: |-
    {
      "API_URL": "https://api-mssql-go.b9e6628.kyma.ondemand.com"
    }